version: "3"
services:
    app:
        build: .
        container_name: ardeployer-dev
        hostname: ardeployer-dev
        stdin_open: true
        tty: true
        working_dir: /usr/src/app
        command: bash
